#include "MeshExporter.hpp"
#include "DepthMapGenerator.hpp"
#include "ExportUtils.hpp"

namespace pelpaint::exporter {

    struct MeshVertex {
        float x = 0.0f;
        float y = 0.0f;
        float z = 0.0f;
        float nx = 0.0f;
        float ny = 0.0f;
        float nz = 1.0f;
        float u = 0.0f;
        float v = 0.0f;
        std::uint8_t r = 255;
        std::uint8_t g = 255;
        std::uint8_t b = 255;
        std::uint8_t a = 255;
    };

    struct MeshData {
        std::vector<MeshVertex> vertices;
        std::vector<std::uint32_t> indices;
    };

    bool MeshExporter::SaveAsMesh(const std::string& filename,
                                  const ImageView& view,
                                  const pelpaint::ColorPalette& palette,
                                  const MeshExportOptions& options)
    {
        (void)palette; // reserved for later palette-based coloring

        if (!view.valid() || options.gridSize == 0) return false;

        std::vector<float> depthMap;
        if (!DepthMapGenerator::BuildDepthMap(view, options.gridSize, depthMap)) {
            return false;
        }

        MeshData mesh;
        switch (options.mode) {
            case MeshMode::Solid:
                if (!BuildSolidMesh(view, depthMap, options.gridSize, options.depthScale, mesh))
                    return false;
                break;
            case MeshMode::Wireframe:
                if (!BuildWireframeMesh(view, depthMap, options.gridSize, options.depthScale, mesh))
                    return false;
                break;
            case MeshMode::LoPoly:
                // TODO
                return false;
            case MeshMode::PixelPerfect:
                if (!BuildPixelPerfectMesh(view, depthMap, options.gridSize, options.depthScale, mesh))
                    return false;
                break;
        }

        std::ofstream file(filename, std::ios::binary | std::ios::trunc);
        if (!file.is_open()) return false;

        const bool writeColors = options.useVertexColors;

        if (options.mode == MeshMode::Wireframe) {
            if ((mesh.indices.size() % 2u) != 0u) return false;
        } else {
            if ((mesh.indices.size() % 3u) != 0u) return false;
        }

        file << "ply\n";
        file << "format ascii 1.0\n";
        file << "comment generated by pelpaint\n";
        file << "element vertex " << mesh.vertices.size() << "\n";
        file << "property float x\n";
        file << "property float y\n";
        file << "property float z\n";
        file << "property float nx\n";
        file << "property float ny\n";
        file << "property float nz\n";
        file << "property uchar red\n";
        file << "property uchar green\n";
        file << "property uchar blue\n";
        file << "property uchar alpha\n";

        if (options.mode == MeshMode::Wireframe) {
            const std::size_t edgeCount = mesh.indices.size() / 2u;
            file << "element edge " << edgeCount << "\n";
            file << "property int vertex1\n";
            file << "property int vertex2\n";
        } else {
            const std::size_t faceCount = mesh.indices.size() / 3u;
            file << "element face " << faceCount << "\n";
            file << "property list uchar int vertex_indices\n";
        }

        file << "end_header\n";

        for (const auto& v : mesh.vertices) {
            const std::uint8_t r = writeColors ? v.r : 255;
            const std::uint8_t g = writeColors ? v.g : 255;
            const std::uint8_t b = writeColors ? v.b : 255;
            const std::uint8_t a = writeColors ? v.a : 255;

            file << v.x << ' ' << v.y << ' ' << v.z << ' '
                 << v.nx << ' ' << v.ny << ' ' << v.nz << ' '
                 << int(r) << ' ' << int(g) << ' ' << int(b) << ' ' << int(a) << '\n';
        }

        if (options.mode == MeshMode::Wireframe) {
            for (std::size_t i = 0; i + 1 < mesh.indices.size(); i += 2) {
                file << mesh.indices[i] << ' ' << mesh.indices[i + 1] << '\n';
            }
        } else {
            for (std::size_t i = 0; i + 2 < mesh.indices.size(); i += 3) {
                file << "3 " << mesh.indices[i] << ' ' << mesh.indices[i + 1] << ' ' << mesh.indices[i + 2] << '\n';
            }
        }

        return file.good();
    }


    static bool BuildMergedRects(std::span<const PixelCell> cells,
                                 std::uint32_t sampleW,
                                 std::uint32_t sampleH,
                                 std::vector<MergeRect>& outRects)
    {
        outRects.clear();

        if (sampleW == 0 || sampleH == 0) return false;
        if (cells.size() != static_cast<std::size_t>(sampleW) * sampleH) return false;

        std::vector<std::uint8_t> visited(cells.size(), 0);

        auto idxOf = [sampleW](std::uint32_t x, std::uint32_t y) noexcept -> std::size_t {
            return static_cast<std::size_t>(y) * sampleW + x;
        };

        auto sameCell = [](const PixelCell& a, const PixelCell& b) noexcept -> bool {
            return a.valid == b.valid &&
                   a.r == b.r && a.g == b.g && a.b == b.b && a.a == b.a;
                   // optionally add depth quantization here:
                   // && std::abs(a.depth - b.depth) < 0.02f;
        };

        for (std::uint32_t y = 0; y < sampleH; ++y) {
            for (std::uint32_t x = 0; x < sampleW; ++x) {
                const std::size_t idx = idxOf(x, y);
                if (visited[idx]) continue;

                const PixelCell& seed = cells[idx];
                visited[idx] = 1;

                if (!seed.valid) continue;

                // Expand width
                std::uint32_t w = 1;
                while (x + w < sampleW) {
                    const std::size_t nidx = idxOf(x + w, y);
                    if (visited[nidx] || !sameCell(cells[nidx], seed)) break;
                    ++w;
                }

                // Expand height
                std::uint32_t h = 1;
                while (y + h < sampleH) {
                    bool rowMatches = true;
                    for (std::uint32_t dx = 0; dx < w; ++dx) {
                        const std::size_t cidx = idxOf(x + dx, y + h);
                        if (visited[cidx] || !sameCell(cells[cidx], seed)) {
                            rowMatches = false;
                            break;
                        }
                    }
                    if (!rowMatches) break;
                    ++h;
                }

                // Mark region visited
                for (std::uint32_t dy = 0; dy < h; ++dy) {
                    for (std::uint32_t dx = 0; dx < w; ++dx) {
                        visited[idxOf(x + dx, y + dy)] = 1;
                    }
                }

                outRects.push_back(MergeRect{ x, y, w, h, seed });
            }
        }

        return true;
    }

    bool MeshExporter::BuildSolidMesh(const ImageView& view,
                                      std::span<const float> depthMap,
                                      std::uint32_t gridSize,
                                      float depthScale,
                                      MeshData& outMesh)
    {
        outMesh.vertices.clear();
        outMesh.indices.clear();

        if (!view.valid() || view.data == nullptr || view.channels < 4) return false;
        if (gridSize == 0 || depthScale == 0.0f) return false;

        const std::size_t sampleW = SampleWidth(view.width, gridSize);
        const std::size_t sampleH = SampleHeight(view.height, gridSize);

        if (depthMap.size() != sampleW * sampleH) return false;
        if (sampleW < 2 || sampleH < 2) return false;

        try {
            outMesh.vertices.resize(sampleW * sampleH);
            outMesh.indices.reserve((sampleW - 1u) * (sampleH - 1u) * 6u);
        } catch (...) {
            return false;
        }

        // Build vertices
        for (std::size_t sy = 0; sy < sampleH; ++sy) {
            const std::uint32_t pxY = std::min<std::uint32_t>(static_cast<std::uint32_t>(sy * gridSize), view.height - 1u);
            const float v = (sampleH > 1) ? (static_cast<float>(sy) / static_cast<float>(sampleH - 1u)) : 0.0f;

            for (std::size_t sx = 0; sx < sampleW; ++sx) {
                const std::uint32_t pxX = std::min<std::uint32_t>(static_cast<std::uint32_t>(sx * gridSize), view.width - 1u);
                const float u = (sampleW > 1) ? (static_cast<float>(sx) / static_cast<float>(sampleW - 1u)) : 0.0f;

                const std::size_t idx = sy * sampleW + sx;
                const float z = depthMap[idx] * depthScale;

                MeshVertex vtx{};
                vtx.x = static_cast<float>(pxX);
                vtx.y = static_cast<float>(pxY);
                vtx.z = z;

                // UVs reserved for later.
                vtx.u = u;
                vtx.v = v;

                // Vertex color from source image
                std::uint8_t r = 255, g = 255, b = 255, a = 255;
                if (!ReadPixelRGBA8(view, pxX, pxY, r, g, b, a)) return false;

                vtx.r = r;
                vtx.g = g;
                vtx.b = b;
                vtx.a = a;

                outMesh.vertices[idx] = vtx;
            }
        }

        // Build triangle indices
        auto vertexIndex = [sampleW](std::size_t x, std::size_t y) noexcept -> std::uint32_t {
            return static_cast<std::uint32_t>(y * sampleW + x);
        };

        for (std::size_t y = 0; y + 1 < sampleH; ++y) {
            for (std::size_t x = 0; x + 1 < sampleW; ++x) {
                const std::uint32_t i0 = vertexIndex(x, y);
                const std::uint32_t i1 = vertexIndex(x + 1, y);
                const std::uint32_t i2 = vertexIndex(x + 1, y + 1);
                const std::uint32_t i3 = vertexIndex(x, y + 1);

                // Two triangles per grid cell
                outMesh.indices.push_back(i0);
                outMesh.indices.push_back(i1);
                outMesh.indices.push_back(i2);

                outMesh.indices.push_back(i0);
                outMesh.indices.push_back(i2);
                outMesh.indices.push_back(i3);
            }
        }

        // Compute normals
        for (std::size_t sy = 0; sy < sampleH; ++sy) {
            for (std::size_t sx = 0; sx < sampleW; ++sx) {
                const std::size_t idx = sy * sampleW + sx;

                const std::size_t xm1 = (sx > 0) ? sx - 1 : sx;
                const std::size_t xp1 = (sx + 1 < sampleW) ? sx + 1 : sx;
                const std::size_t ym1 = (sy > 0) ? sy - 1 : sy;
                const std::size_t yp1 = (sy + 1 < sampleH) ? sy + 1 : sy;

                const float hl = depthMap[sy * sampleW + xm1] * depthScale;
                const float hr = depthMap[sy * sampleW + xp1] * depthScale;
                const float hd = depthMap[ym1 * sampleW + sx] * depthScale;
                const float hu = depthMap[yp1 * sampleW + sx] * depthScale;

                // Gradient-based normal
                const float dx = hl - hr;
                const float dy = hd - hu;

                float nx = dx;
                float ny = dy;
                float nz = 2.0f; // strength bias for smoother normals

                const float len = std::sqrt(nx * nx + ny * ny + nz * nz);
                if (len > 0.0f) {
                    nx /= len;
                    ny /= len;
                    nz /= len;
                } else {
                    nx = 0.0f;
                    ny = 0.0f;
                    nz = 1.0f;
                }

                outMesh.vertices[idx].nx = nx;
                outMesh.vertices[idx].ny = ny;
                outMesh.vertices[idx].nz = nz;
            }
        }

        return true;
    }

    bool MeshExporter::BuildWireframeMesh(const ImageView& view,
                                          std::span<const float> depthMap,
                                          std::uint32_t gridSize,
                                          float depthScale,
                                          MeshData& outMesh)
    {
        outMesh.vertices.clear();
        outMesh.indices.clear();

        if (!view.valid() || view.data == nullptr || view.channels < 4) return false;
        if (gridSize == 0 || depthScale == 0.0f) return false;

        const std::size_t sampleW = SampleWidth(view.width, gridSize);
        const std::size_t sampleH = SampleHeight(view.height, gridSize);

        if (depthMap.size() != sampleW * sampleH) return false;
        if (sampleW < 2 || sampleH < 2) return false;

        try {
            outMesh.vertices.resize(sampleW * sampleH);
            // Wireframe line list: each cell contributes edges
            outMesh.indices.reserve((sampleW - 1u) * (sampleH - 1u) * 8u);
        } catch (...) {
            return false;
        }

        // Build vertices same as solid
        for (std::size_t sy = 0; sy < sampleH; ++sy) {
            const std::uint32_t pxY = std::min<std::uint32_t>(static_cast<std::uint32_t>(sy * gridSize), view.height - 1u);
            const float v = (sampleH > 1) ? (static_cast<float>(sy) / static_cast<float>(sampleH - 1u)) : 0.0f;

            for (std::size_t sx = 0; sx < sampleW; ++sx) {
                const std::uint32_t pxX = std::min<std::uint32_t>(static_cast<std::uint32_t>(sx * gridSize), view.width - 1u);
                const float u = (sampleW > 1) ? (static_cast<float>(sx) / static_cast<float>(sampleW - 1u)) : 0.0f;

                const std::size_t idx = sy * sampleW + sx;
                const float z = depthMap[idx] * depthScale;

                MeshVertex vtx{};
                vtx.x = static_cast<float>(pxX);
                vtx.y = static_cast<float>(pxY);
                vtx.z = z;
                vtx.u = u;
                vtx.v = v;

                std::uint8_t r = 255, g = 255, b = 255, a = 255;
                if (!ReadPixelRGBA8(view, pxX, pxY, r, g, b, a)) return false;

                vtx.r = r;
                vtx.g = g;
                vtx.b = b;
                vtx.a = a;

                outMesh.vertices[idx] = vtx;
            }
        }

        auto vertexIndex = [sampleW](std::size_t x, std::size_t y) noexcept -> std::uint32_t {
            return static_cast<std::uint32_t>(y * sampleW + x);
        };

        // Emit grid line segments:
        // horizontal lines
        for (std::size_t y = 0; y < sampleH; ++y) {
            for (std::size_t x = 0; x + 1 < sampleW; ++x) {
                outMesh.indices.push_back(vertexIndex(x, y));
                outMesh.indices.push_back(vertexIndex(x + 1, y));
            }
        }

        // vertical lines
        for (std::size_t y = 0; y + 1 < sampleH; ++y) {
            for (std::size_t x = 0; x < sampleW; ++x) {
                outMesh.indices.push_back(vertexIndex(x, y));
                outMesh.indices.push_back(vertexIndex(x, y + 1));
            }
        }

        return true;
    }

    static std::uint32_t PushVertex(MeshData& mesh,
                                    float x, float y, float z,
                                    float nx, float ny, float nz,
                                    std::uint8_t r, std::uint8_t g, std::uint8_t b, std::uint8_t a)
    {
        MeshVertex vtx{};
        vtx.x = x;
        vtx.y = y;
        vtx.z = z;
        vtx.nx = nx;
        vtx.ny = ny;
        vtx.nz = nz;
        vtx.r = r;
        vtx.g = g;
        vtx.b = b;
        vtx.a = a;

        mesh.vertices.push_back(vtx);
        return static_cast<std::uint32_t>(mesh.vertices.size() - 1u);
    }

    static bool BuildPixelCells(const ImageView& view,
                                std::span<const float> depthMap,
                                std::uint32_t gridSize,
                                std::vector<PixelCell>& outCells)
    {
        outCells.clear();

        if (!view.valid() || view.data == nullptr || view.channels < 4) return false;
        if (gridSize == 0) return false;

        const std::size_t sampleW = SampleWidth(view.width, gridSize);
        const std::size_t sampleH = SampleHeight(view.height, gridSize);

        if (depthMap.size() != sampleW * sampleH) return false;

        try {
            outCells.resize(sampleW * sampleH);
        } catch (...) {
            return false;
        }

        for (std::size_t sy = 0; sy < sampleH; ++sy) {
            const std::uint32_t baseY = static_cast<std::uint32_t>(sy * gridSize);
            const std::uint32_t centerY = ClampU32(
                baseY + (gridSize / 2u),
                0u,
                view.height - 1u
            );

            for (std::size_t sx = 0; sx < sampleW; ++sx) {
                const std::uint32_t baseX = static_cast<std::uint32_t>(sx * gridSize);
                const std::uint32_t centerX = ClampU32(
                    baseX + (gridSize / 2u),
                    0u,
                    view.width - 1u
                );

                const std::size_t idx = sy * sampleW + sx;

                std::uint8_t r = 0, g = 0, b = 0, a = 0;
                if (!ReadPixelRGBA8(view, centerX, centerY, r, g, b, a)) {
                    return false;
                }

                PixelCell cell{};
                cell.valid = (a != 0);
                cell.r = r;
                cell.g = g;
                cell.b = b;
                cell.a = a;
                cell.depth = cell.valid ? Clamp01(depthMap[idx]) : 0.0f;

                outCells[idx] = cell;
            }
        }

        return true;
    }

    static void PushQuad(MeshData& mesh,
                         std::uint32_t i0, std::uint32_t i1,
                         std::uint32_t i2, std::uint32_t i3);

    static void EmitPrism(MeshData& mesh,
                          float x0, float y0, float x1, float y1,
                          float z0, float z1,
                          std::uint8_t r, std::uint8_t g, std::uint8_t b, std::uint8_t a)
    {
        // Top face vertices
        const std::uint32_t t0 = PushVertex(mesh, x0, y0, z1, 0, 0, 1, r, g, b, a);
        const std::uint32_t t1 = PushVertex(mesh, x1, y0, z1, 0, 0, 1, r, g, b, a);
        const std::uint32_t t2 = PushVertex(mesh, x1, y1, z1, 0, 0, 1, r, g, b, a);
        const std::uint32_t t3 = PushVertex(mesh, x0, y1, z1, 0, 0, 1, r, g, b, a);

        // Bottom face
        const std::uint32_t b0 = PushVertex(mesh, x0, y0, z0, 0, 0, -1, r, g, b, a);
        const std::uint32_t b1 = PushVertex(mesh, x1, y0, z0, 0, 0, -1, r, g, b, a);
        const std::uint32_t b2 = PushVertex(mesh, x1, y1, z0, 0, 0, -1, r, g, b, a);
        const std::uint32_t b3 = PushVertex(mesh, x0, y1, z0, 0, 0, -1, r, g, b, a);

        // Top
        PushQuad(mesh, t0, t1, t2, t3);
        // Bottom
        PushQuad(mesh, b3, b2, b1, b0);

        // Sides
        PushQuad(mesh, b0, b1, t1, t0); // front
        PushQuad(mesh, b1, b2, t2, t1); // right
        PushQuad(mesh, b2, b3, t3, t2); // back
        PushQuad(mesh, b3, b0, t0, t3); // left
    }

    static void PushQuad(MeshData& mesh,
                         std::uint32_t i0, std::uint32_t i1,
                         std::uint32_t i2, std::uint32_t i3)
    {
        mesh.indices.push_back(i0);
        mesh.indices.push_back(i1);
        mesh.indices.push_back(i2);

        mesh.indices.push_back(i0);
        mesh.indices.push_back(i2);
        mesh.indices.push_back(i3);
    }

    bool MeshExporter::BuildPixelPerfectMesh(const ImageView& view,
                                             std::span<const float> depthMap,
                                             std::uint32_t gridSize,
                                             float depthScale,
                                             MeshData& outMesh)
    {
        outMesh.vertices.clear();
        outMesh.indices.clear();

        if (!view.valid() || view.data == nullptr || view.channels < 4) return false;
        if (gridSize == 0) return false;
        if (depthScale == 0.0f) return false;

        const std::size_t sampleW = (view.width + gridSize - 1u) / gridSize;
        const std::size_t sampleH = (view.height + gridSize - 1u) / gridSize;

        if (depthMap.size() != sampleW * sampleH) return false;

        std::vector<PixelCell> cells;
        if (!BuildPixelCells(view, depthMap, gridSize, cells)) {
            return false;
        }

        std::vector<MergeRect> rects;
        if (!BuildMergedRects(cells, static_cast<std::uint32_t>(sampleW), static_cast<std::uint32_t>(sampleH), rects)) {
            return false;
        }

        try {
            // Rough reserve estimate: 8 verts per prism, 12 triangles = 36 indices
            outMesh.vertices.reserve(rects.size() * 8u);
            outMesh.indices.reserve(rects.size() * 36u);
        } catch (...) {
            return false;
        }

        for (const auto& rect : rects) {
            const float x0 = static_cast<float>(rect.x * gridSize);
            const float y0 = static_cast<float>(rect.y * gridSize);
            const float x1 = static_cast<float>((rect.x + rect.w) * gridSize);
            const float y1 = static_cast<float>((rect.y + rect.h) * gridSize);

            const float z0 = 0.0f;
            const float z1 = rect.cell.depth * depthScale;

            EmitPrism(outMesh,
                      x0, y0, x1, y1,
                      z0, z1,
                      rect.cell.r, rect.cell.g, rect.cell.b, rect.cell.a);
        }

        return true;
    }
} // namespace pelpaint::exporter
