#pragma once

/** @file
 * @brief RegionGraph-to-SVG exporter using <path> elements.
 */

#include "RegionGraph.hpp"    // RegionGraph, Region, Vec2, Vec3
#include "RDP.hpp"            // RDP::SimplifyPolygon, RDP::RemoveCollinear
#include "../core/Types.hpp"  // pelpaint::Pixel (bgColor in SvgRegionOptions)

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace pelpaint::exporter {

struct SvgRegionOptions {
    /// Multiply every contour coordinate by this integer factor.
    /// Use > 1 to upscale pixel-art (e.g. scale=4 → each pixel = 4 SVG units).
    int             scale           = 1;

    /// RDP polygon simplification epsilon (pixels).
    ///   > 0  — run RDP::SimplifyPolygon with this tolerance
    ///   0    — remove only exactly collinear points (RDP::RemoveCollinear)
    float           rdpEpsilon      = 0.5f;

    /// When true, prepend a solid-colour <rect> covering the full canvas.
    bool            embedBackground = false;

    /// Background fill colour (only used when embedBackground = true).
    pelpaint::Pixel bgColor         = {255, 255, 255, 255};

    /// When true, emit a viewBox="0 0 W H" attribute on the <svg> element.
    bool            writeViewBox    = true;
};

/**
 * @brief RegionGraph-to-SVG exporter using <path> elements.
 *
 * @details Each Region whose contour has >= 3 vertices is emitted as one
 * filled `<path d="M ... L ... Z"/>` element; its colour comes directly
 * from the IR (Vec3 in [0, 255]). An RDP simplification pass is applied
 * first so output paths are compact even for large pixel-art images.
 *
 * @par Output format
 * @code{.xml}
 *   <?xml version="1.0" encoding="UTF-8"?>
 *   <svg xmlns="http://www.w3.org/2000/svg" width="W" height="H" viewBox="0 0 W H">
 *     <!-- Generated by pelpaint -->
 *     <rect x="0" y="0" width="W" height="H" fill="#rrggbb"/>
 *     <path d="M x0,y0 L x1,y1 x2,y2 ... Z" fill="rgb(r,g,b)"/>
 *     ...
 *   </svg>
 * @endcode
 */
class SvgRegionExporter {
public:
    /// Write `graph` to `filename` as an SVG document.
    ///
    /// @param filename  Destination file path.
    /// @param graph     Populated RegionGraph IR (canvasW / canvasH must be set).
    /// @param opts      Formatting options.
    ///
    /// @return true on success; false if the file cannot be opened or
    ///         the graph has no regions with a usable contour.
    static bool SaveAsSvg(
        const std::string&               filename,
        const pelpaint::ir::RegionGraph& graph,
        const SvgRegionOptions&          opts = {})
    {
        if (graph.regions.empty()) return false;

        const int           S    = std::max(1, opts.scale);
        const std::uint32_t svgW = graph.canvasW * static_cast<std::uint32_t>(S);
        const std::uint32_t svgH = graph.canvasH * static_cast<std::uint32_t>(S);

        std::ofstream f(filename, std::ios::trunc);
        if (!f.is_open()) return false;

        f << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          << "<svg xmlns=\"http://www.w3.org/2000/svg\""
          << " width=\""  << svgW << "\""
          << " height=\"" << svgH << "\"";

        if (opts.writeViewBox)
            f << " viewBox=\"0 0 " << svgW << ' ' << svgH << "\"";

        f << ">\n"
          << "  <!-- Generated by pelpaint -->\n";

        if (opts.embedBackground) {
            f << "  <rect x=\"0\" y=\"0\""
              << " width=\""  << svgW << "\""
              << " height=\"" << svgH << "\""
              << " fill=\""   << RgbHex(opts.bgColor.r,
                                        opts.bgColor.g,
                                        opts.bgColor.b) << "\"/>\n";
        }

        for (const pelpaint::ir::Region& region : graph.regions) {
            if (region.contour.size() < 3) continue;

            // Optionally simplify the contour before writing
            const std::vector<pelpaint::ir::Vec2> pts =
                (opts.rdpEpsilon > 0.f)
                    ? pelpaint::ir::RDP::SimplifyPolygon(region.contour, opts.rdpEpsilon)
                    : pelpaint::ir::RDP::RemoveCollinear(region.contour);

            if (pts.size() < 3) continue;

            // Scale a contour coordinate to SVG units (rounds to nearest int)
            auto sv = [S](float v) -> int {
                return static_cast<int>(std::round(v * static_cast<float>(S)));
            };

            // Path data:  M x0,y0 L x1,y1 x2,y2 ... Z
            //   "M" moves to the first vertex, "L" draws lines to all
            //   subsequent vertices (the L command accepts a sequence of
            //   coordinate pairs), "Z" closes the path back to the start.
            f << "  <path d=\"M " << sv(pts[0].x) << ',' << sv(pts[0].y);

            if (pts.size() >= 2) {
                f << " L " << sv(pts[1].x) << ',' << sv(pts[1].y);
                for (std::size_t i = 2; i < pts.size(); ++i)
                    f << ' ' << sv(pts[i].x) << ',' << sv(pts[i].y);
            }

            f << " Z\" fill=\"" << RgbFunc(region.color) << "\"/>\n";
        }

        f << "</svg>\n";
        return f.good();
    }

private:
    /// Format r, g, b as  #rrggbb  (lowercase hex, for the background rect).
    static std::string RgbHex(std::uint8_t r, std::uint8_t g, std::uint8_t b)
    {
        char buf[8];
        std::snprintf(buf, sizeof(buf), "#%02x%02x%02x", r, g, b);
        return std::string(buf);
    }

    /// Format a Vec3 (values in [0, 255]) as  rgb(r,g,b)  for path fill.
    /// Each channel is rounded to the nearest integer and clamped to [0, 255].
    static std::string RgbFunc(const pelpaint::ir::Vec3& c)
    {
        auto ch = [](float v) -> int {
            return static_cast<int>(std::round(std::clamp(v, 0.f, 255.f)));
        };
        char buf[24];
        std::snprintf(buf, sizeof(buf), "rgb(%d,%d,%d)", ch(c.x), ch(c.y), ch(c.z));
        return std::string(buf);
    }
};

} // namespace pelpaint::exporter
